// src/routes/books/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import CatalogSlip from '$lib/components/CatalogSlip.svelte';
	import Seo from '$lib/components/Seo.svelte';
	import VirtualWindow from '$lib/components/VirtualWindow.svelte';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import * as Alert from '$lib/components/ui/alert/index.js';
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();
	const activeName = $derived(data.categories.find((cat) => cat.slug === data.odbor)?.name);
</script>

<Seo
	title="Katalóg"
	description="Prehľadaj školský fond SPŠT podľa názvu, autora, signatúry alebo odboru. Voľné výtlačky uvidíš hneď."
/>

<p class="text-muted-foreground text-sm">
	{data.books.length.toLocaleString('sk-SK')} kníh
	{#if data.q}pre „{data.q}“{/if}
	{#if activeName}· {activeName}{/if}
	{#if data.books.length > 48}
		<span class="hidden sm:inline">· virtualizovaný register</span>
	{/if}
</p>

<div class="mt-4 flex flex-wrap gap-2">
	<Badge href={resolve('/books')} variant={!data.odbor ? 'default' : 'outline'} class="h-8">
		Všetko
	</Badge>
	{#each data.categories as cat (cat.id)}
		<Badge
			href="{resolve('/books')}?odbor={cat.slug}{data.q ? `&q=${encodeURIComponent(data.q)}` : ''}"
			variant={data.odbor === cat.slug ? 'default' : 'outline'}
			class="h-8"
		>
			<span class="sm:hidden">{cat.code}</span>
			<span class="hidden sm:inline">{cat.name}</span>
		</Badge>
	{/each}
</div>

{#if data.books.length === 0}
	<Alert.Root class="mt-10">
		<Alert.Title>Nič sa nenašlo</Alert.Title>
		<Alert.Description>Skús iné slovo, alebo zruš filter.</Alert.Description>
		<Alert.Action>
			<Button href={resolve('/books')} variant="outline" size="sm">Zrušiť filter</Button>
		</Alert.Action>
	</Alert.Root>
{:else}
	<div class="mt-8">
		<VirtualWindow count={data.books.length} estimateSize={() => 88}>
			{#snippet children({ row })}
				{@const book = data.books[row.index]}
				{#if book}
					<CatalogSlip {book} />
				{/if}
			{/snippet}
		</VirtualWindow>
	</div>
{/if}

// src/app/(desk)/books/page.tsx
import { pageMeta } from '@/utils/metadata';
import { listBookSlips, listCategoryChips } from '@/server/library';
import { CatalogSlip } from '@/components/CatalogSlip';
import { VirtualWindow } from '@/components/VirtualWindow';

export const metadata = pageMeta({
	title: 'Katalóg',
	description: 'Prehľadaj školský fond SPŠT podľa názvu, autora, signatúry alebo odboru. Voľné výtlačky uvidíš hneď.'
});

export default async function BooksPage({
	searchParams
}: {
	searchParams: Promise<{ q?: string; odbor?: string }>;
}) {
	const params = await searchParams;
	const q = params.q ?? '';
	const odbor = params.odbor ?? '';
	const [slips, categories] = await Promise.all([listBookSlips(q || undefined), listCategoryChips()]);
	const books = odbor ? slips.filter((item) => item.category.slug === odbor) : slips;
	const activeName = categories.find((cat) => cat.slug === odbor)?.name;

	return (
		<>
			<p className="text-muted-foreground text-sm">
				{books.length.toLocaleString('sk-SK')} kníh
				{q ? ` pre „${q}“` : ''}
				{activeName ? ` · ${activeName}` : ''}
				{books.length > 48 ? <span className="hidden sm:inline"> · virtualizovaný register</span> : null}
			</p>
			<div className="mt-4 flex flex-wrap gap-2">
				<a
					href="/books"
					className={`inline-flex h-8 items-center rounded-full px-3 text-sm no-underline ${!odbor ? 'bg-primary text-primary-foreground' : 'ring-1 ring-border'}`}
				>
					Všetko
				</a>
				{categories.map((cat) => (
					<a
						key={cat.id}
						href={`/books?odbor=${cat.slug}${q ? `&q=${encodeURIComponent(q)}` : ''}`}
						className={`inline-flex h-8 items-center rounded-full px-3 text-sm no-underline ${odbor === cat.slug ? 'bg-primary text-primary-foreground' : 'ring-1 ring-border'}`}
					>
						<span className="sm:hidden">{cat.code}</span>
						<span className="hidden sm:inline">{cat.name}</span>
					</a>
				))}
			</div>
			{books.length === 0 ? (
				<div className="mt-10 rounded-2xl ring-1 ring-border p-6">
					<p className="font-display text-xl">Nič sa nenašlo</p>
					<p className="text-muted-foreground mt-2">Skús iné slovo, alebo zruš filter.</p>
					<a href="/books" className="mt-4 inline-block text-sm underline">
						Zrušiť filter
					</a>
				</div>
			) : (
				<div className="mt-8">
					<VirtualWindow count={books.length} estimateSize={() => 88}>
						{(index) => {
							const book = books[index];
							return book ? <CatalogSlip book={book} /> : null;
						}}
					</VirtualWindow>
				</div>
			)}
		</>
	);
}
