// src/app/(desk)/loans/page.tsx
import { pageMeta } from '@/utils/metadata';
import { authorLine, dueStatus, firstName, loanedLabel, readerNumber } from '@/utils/format';
import { BookCover } from '@/components/BookCover';
import { loadLoans, returnLoan, renewLoanAction, cancelWait, clearHistory } from './actions';
import '@/components/loans-folio.css';

export const metadata = pageMeta({
	title: 'Moja knižnica',
	description: 'Aktívne výpožičky a vrátenia v školskej knižnici SPŠT.',
	index: false
});

export default async function LoansPage() {
	const data = await loadLoans();
	const serial = readerNumber(data.reader.id);
	const given = firstName(data.reader.name);

	return (
		<section className="folio">
			<div className="folio-copy">
				<p className="folio-kicker">pavilón B · lehota na lístku</p>
				<p className="folio-display">Koľko treba.</p>
				<p className="folio-lede">
					{given}, pri výpožičke vyplníš meno, triedu a dobu. Ber si toľko zväzkov, koľko potrebuješ — strop na
					preukaze nie je.
				</p>
				<ul className="folio-facts">
					<li>7–21 dní</li>
					<li>bez stropu</li>
					<li>pav. B</li>
				</ul>
			</div>
			<article className="folio-card">
				<span className="folio-spine" aria-hidden="true" />
				<header className="folio-id">
					<p className="folio-mark">výpožičný lístok</p>
					<p className="folio-serial">{serial}</p>
					<h1>{data.reader.name}</h1>
					<p>
						{loanedLabel(data.activeCount)} · {data.waits.length} v rade
					</p>
				</header>
				{data.loans.length === 0 ? (
					<p className="text-muted-foreground mt-6">Žiadny zväzok práve nie je na preukaze.</p>
				) : (
					<ul className="mt-6 grid gap-4">
						{data.loans.map((item) => {
							const due = dueStatus(item.dueAt);
							return (
								<li key={item.id} className="flex gap-4 border-t border-border pt-4">
									<BookCover book={item.book} size="thumb" />
									<div className="min-w-0">
										<p className="font-mono text-[0.62rem] tracking-[0.12em] uppercase text-muted-foreground">
											{item.book.callNumber}
										</p>
										<a href={`/books/${item.book.id}`} className="font-display text-xl no-underline">
											{item.book.title}
										</a>
										<p className="text-muted-foreground text-sm">{authorLine(item.book.authors)}</p>
										<p className="mt-2 text-sm">{due.label}</p>
										<div className="mt-3 flex flex-wrap gap-2">
											<form action={returnLoan}>
												<input type="hidden" name="loanId" value={item.id} />
												<button type="submit" className="rounded-full bg-primary px-3 py-1.5 text-sm text-primary-foreground">
													Nahlásiť vrátenie
												</button>
											</form>
											{item.canRenew ? (
												<form action={renewLoanAction}>
													<input type="hidden" name="loanId" value={item.id} />
													<button type="submit" className="rounded-full px-3 py-1.5 text-sm ring-1 ring-border">
														Predĺžiť
													</button>
												</form>
											) : null}
										</div>
									</div>
								</li>
							);
						})}
					</ul>
				)}
				{data.waits.length ? (
					<section className="mt-10">
						<h2 className="font-display text-2xl">V rade</h2>
						<ul className="mt-4 grid gap-3">
							{data.waits.map((wait) => (
								<li key={wait.id} className="flex items-center justify-between gap-3">
									<a href={`/books/${wait.book.id}`} className="no-underline">
										{wait.book.title} · {wait.place}. miesto
									</a>
									<form action={cancelWait}>
										<input type="hidden" name="reservationId" value={wait.id} />
										<button type="submit" className="text-sm underline">
											Stiahnuť
										</button>
									</form>
								</li>
							))}
						</ul>
					</section>
				) : null}
				{data.history.length ? (
					<section className="mt-10">
						<div className="flex items-center justify-between">
							<h2 className="font-display text-2xl">Vrátené</h2>
							<form action={clearHistory}>
								<button type="submit" className="text-sm underline">
									Vyčistiť
								</button>
							</form>
						</div>
						<ul className="mt-4 grid gap-2">
							{data.history.map((item) => (
								<li key={item.id}>
									<a href={`/books/${item.book.id}`} className="no-underline">
										{item.book.title}
									</a>
								</li>
							))}
						</ul>
					</section>
				) : null}
			</article>
		</section>
	);
}

// src/routes/loans/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { enhance } from '$app/forms';
	import BookCover from '$lib/components/BookCover.svelte';
	import StampBurst from '$lib/components/StampBurst.svelte';
	import { dueStatus, readerNumber, shortDate } from '$lib/format';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Progress } from '$lib/components/ui/progress/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import * as Alert from '$lib/components/ui/alert/index.js';
	import * as Tabs from '$lib/components/ui/tabs/index.js';
	import type { ActionData, PageProps } from './$types';
	import Seo from '$lib/components/Seo.svelte';

	let { data, form }: PageProps & { form: ActionData } = $props();
	const progress = $derived((data.activeCount / data.maxLoans) * 100);
</script>

<Seo
	title="Moja knižnica"
	description="Aktívne výpožičky a vrátenia v školskej knižnici SPŠT."
	index={false}
/>

{#if form && 'stamp' in form && form.stamp}
	<StampBurst label={form.stamp} sub={form.sub} />
{/if}

<p class="text-muted-foreground text-sm text-pretty">
	{data.reader.name} · preukaz {readerNumber(data.reader.id)} · {data.activeCount} z {data.maxLoans} miest
</p>
<Progress class="mt-4 max-w-md" max={100} value={progress} />

{#if form && 'message' in form && form.message}
	<Alert.Root variant="destructive" class="mt-4">
		<Alert.Description>{form.message}</Alert.Description>
	</Alert.Root>
{/if}

<Tabs.Root value="aktivne" class="mt-8">
	<Tabs.List class="h-auto w-full">
		<Tabs.Trigger value="aktivne" class="px-2 text-[0.8rem] sm:text-sm">Požičané ({data.loans.length})</Tabs.Trigger>
		<Tabs.Trigger value="historia" class="px-2 text-[0.8rem] sm:text-sm">Vrátené ({data.history.length})</Tabs.Trigger>
	</Tabs.List>
	<Tabs.Content value="aktivne" class="mt-6">
		{#if data.loans.length === 0}
			<Alert.Root>
				<Alert.Title>Zatiaľ nič nepožičiavaš</Alert.Title>
				<Alert.Description>Vyber knihu z katalógu a vypožičaj si ju na 21 dní.</Alert.Description>
				<Alert.Action>
					<Button href={resolve('/books')} size="sm">Otvoriť katalóg</Button>
				</Alert.Action>
			</Alert.Root>
		{:else}
			<div class="grid gap-4 md:grid-cols-2">
				{#each data.loans as item (item.id)}
					{@const due = dueStatus(item.dueAt)}
					<Card.Root class="overflow-hidden py-0">
						<Card.Content class="flex gap-4 p-4">
							<BookCover book={item.book} size="thumb" />
							<div class="flex min-w-0 flex-1 flex-col justify-between">
								<div>
									<Badge variant={due.tone === 'ok' ? 'secondary' : 'destructive'}>{due.label}</Badge>
									<Card.Title class="mt-2 text-[1.05rem] leading-snug break-words sm:text-xl">
										<a href={resolve('/books/[id]', { id: item.book.id })} class="hover:text-primary">
											{item.book.title}
										</a>
									</Card.Title>
									<Card.Description>Od {shortDate(item.borrowedAt)}</Card.Description>
								</div>
								<form class="mt-4" method="POST" action="?/return" use:enhance>
									<input type="hidden" name="loanId" value={item.id} />
									<Button type="submit" variant="destructive" size="sm">Vrátiť</Button>
								</form>
							</div>
						</Card.Content>
					</Card.Root>
				{/each}
			</div>
		{/if}
	</Tabs.Content>
	<Tabs.Content value="historia" class="mt-6">
		{#if data.history.length === 0}
			<p class="text-muted-foreground">Ešte žiadna vrátená kniha.</p>
		{:else}
			<ul class="divide-border divide-y">
				{#each data.history as item (item.id)}
					<li class="flex flex-wrap justify-between gap-2 py-3">
						<a class="hover:text-primary font-medium" href={resolve('/books/[id]', { id: item.book.id })}>
							{item.book.title}
						</a>
						<span class="text-muted-foreground text-sm">
							{item.returnedAt ? shortDate(item.returnedAt) : ''}
						</span>
					</li>
				{/each}
			</ul>
		{/if}
	</Tabs.Content>
</Tabs.Root>
