// src/app/(desk)/books/[id]/page.tsx
import { notFound } from 'next/navigation';
import { pageMeta } from '@/utils/metadata';
import {
	borrowBook,
	getActiveLoan,
	getBook,
	getLastBorrower,
	countActiveLoans,
	MAX_ACTIVE_LOANS,
	relatedBookSlips
} from '@/server/library';
import { bookHoldUserId, getOpenHold, reserveBook } from '@/server/waitlist';
import { queueHoldNotice } from '@/server/hold-mail';
import { hasBorrowErrors, normalizeClass, parseLoanDays, splitReaderName, validateBorrow } from '@/desk/borrow-fields';
import { copiesLabel, shortDate, stampDate } from '@/utils/format';
import { queueLoanNotice } from '@/server/loan-mail';
import { getSessionReader } from '@/server/session';
import { BookCover } from '@/components/BookCover';
import { CatalogSlip } from '@/components/CatalogSlip';
import { BorrowDialog } from '@/components/BorrowDialog';
import { redirect } from 'next/navigation';

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
	const { id } = await params;
	const book = await getBook(id);
	if (!book) return pageMeta({ title: 'Karta chýba', description: 'Zväzok v katalógu nie je.', index: false });
	return pageMeta({ title: book.title, description: book.description, type: 'book' });
}

async function borrowAction(formData: FormData) {
	'use server';
	const user = await getSessionReader();
	if (!user) redirect('/login');
	const id = String(formData.get('bookId') ?? '');
	const values = {
		firstName: formData.get('firstName')?.toString() ?? '',
		lastName: formData.get('lastName')?.toString() ?? '',
		className: formData.get('className')?.toString() ?? '',
		days: formData.get('days')?.toString() ?? ''
	};
	const errors = validateBorrow(values);
	if (hasBorrowErrors(errors)) return;
	const days = parseLoanDays(values.days);
	if (!days) return;
	const result = await borrowBook(user.id, id, {
		firstName: values.firstName.trim(),
		lastName: values.lastName.trim(),
		className: normalizeClass(values.className),
		days
	});
	if (!result.ok) return;
	const held = await getBook(id);
	await queueLoanNotice({
		kind: 'borrow',
		to: user.email,
		readerName: `${values.firstName.trim()} ${values.lastName.trim()}`.trim() || user.name,
		bookTitle: held?.title ?? 'Zväzok',
		callNumber: held?.callNumber,
		dueAt: result.dueAt,
		className: normalizeClass(values.className),
		days
	});
	redirect(`/books/${id}?ok=borrow`);
}

async function reserveAction(formData: FormData) {
	'use server';
	const user = await getSessionReader();
	if (!user) redirect('/login');
	const id = String(formData.get('bookId') ?? '');
	const result = await reserveBook(user.id, id);
	if (!result.ok) return;
	const held = await getBook(id);
	await queueHoldNotice({
		kind: 'queued',
		to: user.email,
		readerName: user.name,
		bookTitle: held?.title ?? 'Zväzok',
		callNumber: held?.callNumber,
		place: result.place
	});
	redirect(`/books/${id}?ok=hold`);
}

export default async function BookPage({
	params,
	searchParams
}: {
	params: Promise<{ id: string }>;
	searchParams: Promise<{ ok?: string }>;
}) {
	const { id } = await params;
	const { ok } = await searchParams;
	const current = await getBook(id);
	if (!current) notFound();
	const user = await getSessionReader();
	const [userLoan, activeCount, lastBorrower, related, wait, holdUserId] = await Promise.all([
		user ? getActiveLoan(user.id, current.id) : null,
		user ? countActiveLoans(user.id) : 0,
		user ? getLastBorrower(user.id) : null,
		relatedBookSlips(current.id, current.category.id),
		user ? getOpenHold(user.id, current.id) : null,
		bookHoldUserId(current.id)
	]);
	const fromName = user ? splitReaderName(user.name) : { firstName: '', lastName: '' };
	const borrower = lastBorrower ?? {
		firstName: fromName.firstName,
		lastName: fromName.lastName,
		className: '',
		days: 21
	};
	const available = current.copiesAvailable > 0;
	const atLimit = MAX_ACTIVE_LOANS != null && activeCount >= MAX_ACTIVE_LOANS;

	return (
		<article>
			<p className="text-muted-foreground text-sm">
				<a href="/books" className="no-underline hover:underline">
					Katalóg
				</a>
				{' · '}
				<a href={`/departments/${current.category.slug}`} className="no-underline hover:underline">
					{current.category.name}
				</a>
			</p>
			{ok === 'borrow' ? <p className="mt-4 font-display text-2xl">Vypožičané. {stampDate(new Date())}</p> : null}
			{ok === 'hold' ? <p className="mt-4 font-display text-2xl">Si v rade.</p> : null}
			<div className="mt-8 grid gap-10 lg:grid-cols-[auto_minmax(0,1fr)]">
				<BookCover book={current} size="hero" linked={false} />
				<div>
					<p className="font-mono text-[0.72rem] tracking-[0.16em] uppercase text-muted-foreground">
						{current.category.code} · {current.callNumber}
					</p>
					<h1 className="font-display mt-2 text-[clamp(2rem,6vw,3.4rem)] leading-[0.95] font-semibold tracking-[-0.04em]">
						{current.title}
					</h1>
					<p className="mt-3 text-lg">{current.authors.map((person) => person.name).join(' · ')}</p>
					<p className="text-muted-foreground mt-4 max-w-[52ch] leading-relaxed">{current.description}</p>
					<p className="mt-6 font-sans text-sm font-semibold uppercase tracking-wide">
						{copiesLabel(current.copiesAvailable, current.copiesTotal)}
					</p>
					{userLoan ? (
						<p className="mt-4">Máš tento zväzok do {shortDate(userLoan.dueAt)}.</p>
					) : wait ? (
						<p className="mt-4">Čakáš v rade.</p>
					) : available && user && !atLimit ? (
						<BorrowDialog
							bookId={current.id}
							title={current.title}
							callNumber={current.callNumber}
							borrower={borrower}
							action={borrowAction}
						/>
					) : !available && user ? (
						<form action={reserveAction} className="mt-8">
							<input type="hidden" name="bookId" value={current.id} />
							<button type="submit" className="rounded-full bg-primary px-5 py-2.5 text-primary-foreground">
								Zaradiť do radu
							</button>
						</form>
					) : !user ? (
						<p className="mt-6">
							<a href="/login" className="underline">
								Prihlás sa
							</a>
							, potom si zväzok požičiaš.
						</p>
					) : null}
				</div>
			</div>
			{related.length ? (
				<section className="mt-16">
					<h2 className="font-display text-2xl">Ďalšie z police</h2>
					<div className="mt-4">
						{related.map((book) => (
							<CatalogSlip key={book.id} book={book} />
						))}
					</div>
				</section>
			) : null}
		</article>
	);
}

// src/routes/books/[id]/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import BookCover from '$lib/components/BookCover.svelte';
	import BorrowSlip from '$lib/components/BorrowSlip.svelte';
	import LockerCard from '$lib/components/LockerCard.svelte';
	import StampBurst from '$lib/components/StampBurst.svelte';
	import Seo from '$lib/components/Seo.svelte';
	import { jacketFor } from '$lib/cover';
	import { copiesLabel, loanedLabel, shortDate } from '$lib/format';
	import {
		hasBorrowErrors,
		normalizeClass,
		parseLoanDays,
		type BorrowErrors
	} from '$lib/borrow-fields';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import * as Alert from '$lib/components/ui/alert/index.js';
	import * as Breadcrumb from '$lib/components/ui/breadcrumb/index.js';
	import type { ActionData, PageProps } from './$types';

	let { data, form }: PageProps & { form: ActionData } = $props();
	const book = $derived(data.book);
	const available = $derived(book.copiesAvailable > 0);
	const atLimit = $derived(data.maxLoans != null && data.activeCount >= data.maxLoans);
	const formValues = $derived(form && 'values' in form ? form.values : undefined);
	const formErrors = $derived(
		(form && 'errors' in form ? form.errors : undefined) as BorrowErrors | undefined
	);
	const borrower = $derived({
		firstName: formValues?.firstName ?? data.borrower.firstName,
		lastName: formValues?.lastName ?? data.borrower.lastName,
		className: formValues?.className ? normalizeClass(formValues.className) : data.borrower.className,
		days: parseLoanDays(formValues?.days ?? '') ?? data.borrower.days
	});
	const slipFail = $derived(
		Boolean(form && 'errors' in form && hasBorrowErrors(form.errors ?? {}))
	);
	let slipOpen = $state(false);

	$effect(() => {
		if (form && 'stamp' in form && form.stamp) slipOpen = false;
		else if (form && 'errors' in form) slipOpen = true;
	});
</script>

<Seo
	title={book.title}
	description={book.description}
	type="book"
	image={jacketFor(book).photo}
	jsonLd={{
		'@context': 'https://schema.org',
		'@type': 'Book',
		name: book.title,
		isbn: book.isbn,
		numberOfPages: book.pages,
		author: book.authors.map((person) => ({ '@type': 'Person', name: person.name }))
	}}
/>

{#if form && 'stamp' in form && form.stamp}
	<StampBurst label={form.stamp} sub={form.sub} />
{/if}

<Breadcrumb.Root>
	<Breadcrumb.List>
		<Breadcrumb.Item>
			<Breadcrumb.Link href={resolve('/books')}>Katalóg</Breadcrumb.Link>
		</Breadcrumb.Item>
		<Breadcrumb.Separator />
		<Breadcrumb.Item>
			<Breadcrumb.Link href={resolve('/departments/[slug]', { slug: book.category.slug })}>
				{book.category.name}
			</Breadcrumb.Link>
		</Breadcrumb.Item>
		<Breadcrumb.Separator />
		<Breadcrumb.Item class="min-w-0">
			<Breadcrumb.Page class="block max-w-[16ch] truncate sm:max-w-[28ch]">{book.title}</Breadcrumb.Page>
		</Breadcrumb.Item>
	</Breadcrumb.List>
</Breadcrumb.Root>

<article class="mt-5 grid items-start justify-items-center gap-5 sm:mt-8 sm:gap-10 md:grid-cols-[auto_1fr] md:justify-items-stretch">
	<BookCover {book} size="hero" linked={false} />
	<div class="min-w-0 w-full">
		<Badge variant={available ? 'secondary' : 'destructive'}>
			{copiesLabel(book.copiesAvailable, book.copiesTotal)}
		</Badge>
		<h2 class="mt-3 font-serif text-[1.7rem] leading-[1.05] font-bold break-words sm:text-[2.05rem] md:text-5xl">{book.title}</h2>
		{#if book.subtitle}
			<p class="text-muted-foreground mt-2 text-lg">{book.subtitle}</p>
		{/if}
		<p class="mt-4">
			{#each book.authors as person, i (person.id)}
				<a
					class="font-semibold underline-offset-4 hover:underline"
					href={resolve('/authors/[slug]', { slug: person.slug })}
				>
					{person.name}
				</a>{#if i < book.authors.length - 1}, {/if}
			{/each}
		</p>
		<p class="text-muted-foreground mt-2 text-sm break-words">
			{book.publisher}, {book.year} · {book.pages} s. · ISBN {book.isbn} · {book.callNumber}
		</p>
		<p class="mt-5 max-w-xl font-serif text-[1.05rem] leading-relaxed sm:text-lg">{book.description}</p>
		<Separator class="my-6" />

		{#if form && 'message' in form && form.message && !slipFail}
			<Alert.Root variant="destructive" class="mb-4">
				<Alert.Title>Nešlo to</Alert.Title>
				<Alert.Description>{form.message}</Alert.Description>
			</Alert.Root>
		{/if}

		<div class="flex flex-col items-stretch gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
			{#if data.userLoan}
				<p class="text-sm">U teba do <strong>{shortDate(data.userLoan.dueAt)}</strong></p>
				<Button href={resolve('/loans')}>Vrátiť v Moja knižnica</Button>
			{:else if !data.user}
				<p class="text-muted-foreground text-sm">Na výpožičku treba účet.</p>
				<Button href={resolve('/login')}>Prihlásiť sa</Button>
			{:else}
				<p class="text-muted-foreground text-sm">
					{#if !available}
						Momentálne nie je voľný výtlačok.
					{:else if atLimit}
						Limit {data.maxLoans} výpožičiek je plný.
					{:else}
						7–90 dní · {loanedLabel(data.activeCount)} u teba
					{/if}
				</p>
				<Button type="button" disabled={!available || atLimit} onclick={() => (slipOpen = true)}>
					Vypožičať
				</Button>
				<BorrowSlip
					title={book.title}
					defaults={borrower}
					errors={formErrors ?? {}}
					message={form && 'errors' in form ? form.message : ''}
					bind:open={slipOpen}
				/>
			{/if}
		</div>
	</div>
</article>

{#if data.related.length}
	<section class="mt-14">
		<h2 class="text-xl font-bold">Ďalšie z odboru</h2>
		<div class="cover-grid mt-5">
			{#each data.related as item (item.id)}
				<LockerCard book={item} />
			{/each}
		</div>
	</section>
{/if}
