// src/lib/components/HallChrome.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import { onMount } from 'svelte';
	import { cubicOut } from 'svelte/easing';
	import { fly } from 'svelte/transition';
	import BookOpenIcon from '@lucide/svelte/icons/book-open';
	import SearchIcon from '@lucide/svelte/icons/search';
	import UserIcon from '@lucide/svelte/icons/user';
	import CatalogSearch from '$lib/components/CatalogSearch.svelte';
	import ThemeToggle from '$lib/components/ThemeToggle.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import type { CatalogSearchItem } from '$lib/search';
	import type { Reader } from '$lib/types';
	import type { Snippet } from 'svelte';

	let {
		user,
		admin = false,
		searchPreview,
		children
	}: {
		user: Reader;
		admin?: boolean;
		searchPreview: CatalogSearchItem[];
		children: Snippet;
	} = $props();

	let menuOpen = $state(false);
	let searchOpen = $state(false);
	const path = $derived(page.url.pathname);

	onMount(() => {
		const onKey = (event: KeyboardEvent) => {
			if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
				event.preventDefault();
				openSearch();
			}
		};
		window.addEventListener('keydown', onKey);
		return () => window.removeEventListener('keydown', onKey);
	});

	function closeMenu() {
		menuOpen = false;
	}

	function openSearch() {
		menuOpen = false;
		searchOpen = true;
	}
</script>

<div class="landing">
	<div class="landing-body" class:is-blurred={searchOpen}>
		<header class="hall-nav">
			<a href={resolve('/')} class="hall-logo no-underline" aria-label="SPŠT knižnica">
				<BookOpenIcon class="size-6" />
			</a>
			<nav class="hall-desk-links" aria-label="Hlavná navigácia">
				<a href={resolve('/')} aria-current={path === '/' ? 'page' : undefined}>Fond</a>
				<a href={resolve('/discover')} aria-current={path.startsWith('/discover') ? 'page' : undefined}>
					Objavovať
				</a>
				<a href={resolve('/holdings')} aria-current={path.startsWith('/holdings') ? 'page' : undefined}>
					Všetky knihy
				</a>
				<a href={resolve('/books')}>Katalóg</a>
				<a href={resolve('/authors')}>Autori</a>
			</nav>
			<div class="hall-tools">
				<button type="button" class="hall-search-btn" onclick={openSearch} aria-label="Hľadať knihu">
					<SearchIcon class="size-4" />
					<span>Hľadať knihu</span>
				</button>
				<ThemeToggle variant="hall" />
				<a
					class="hall-login no-underline"
					href={user ? resolve('/loans') : resolve('/login')}
					aria-label={user ? 'Moje knihy' : 'Prihlásiť sa'}
				>
					<UserIcon class="size-4" />
					<span>{user ? 'Moje knihy' : 'Prihlásiť sa'}</span>
				</a>
				<button
					type="button"
					class="hall-menu-btn"
					class:is-open={menuOpen}
					aria-controls="landing-menu"
					aria-expanded={menuOpen}
					aria-label={menuOpen ? 'Zavrieť menu' : 'Otvoriť menu'}
					onclick={() => (menuOpen = !menuOpen)}
				>
					<span></span>
					<span></span>
					<span></span>
				</button>
			</div>
		</header>

		{#if menuOpen}
			<nav
				class="hall-drawer"
				id="landing-menu"
				aria-label="Mobilné menu"
				transition:fly={{ y: -18, duration: 380, easing: cubicOut }}
			>
				<a href={resolve('/')} onclick={closeMenu}>Fond</a>
				<a href={resolve('/discover')} onclick={closeMenu}>Objavovať</a>
				<a href={resolve('/holdings')} onclick={closeMenu}>Všetky knihy</a>
				<a href={resolve('/books')} onclick={closeMenu}>Katalóg</a>
				<a href={resolve('/departments')} onclick={closeMenu}>Odbory</a>
				<a href={resolve('/authors')} onclick={closeMenu}>Autori</a>
				{#if user}
					<a href={resolve('/profile')} onclick={closeMenu}>Môj profil</a>
					<a href={resolve('/loans')} onclick={closeMenu}>Moje knihy</a>
					{#if admin}
						<a href={resolve('/admin')} onclick={closeMenu}>Pult</a>
					{/if}
				{:else}
					<a href={resolve('/login')} onclick={closeMenu}>Prihlásiť sa</a>
				{/if}
				<div class="hall-drawer-tools">
					<ThemeToggle variant="hall" />
					<button type="button" class="hall-search-btn is-mobile" onclick={openSearch}>
						<SearchIcon class="size-4" />
						<span>Hľadať knihu</span>
					</button>
				</div>
			</nav>
		{/if}

		{@render children()}
		<Footer tone="hall" />
	</div>

	<CatalogSearch preview={searchPreview} bind:open={searchOpen} />
</div>

// src/components/HallChrome.tsx
'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';
import { BookOpen, Search, User } from 'lucide-react';
import type { CatalogSearchItem } from '@/catalog/search';
import type { Reader } from '@/types';
import { CatalogSearch } from './CatalogSearch';
import { ThemeToggle } from './ThemeToggle';
import { Footer } from './Footer';

export function HallChrome({
	user,
	admin = false,
	searchPreview,
	children
}: {
	user: Reader;
	admin?: boolean;
	searchPreview: CatalogSearchItem[];
	children: ReactNode;
}) {
	const path = usePathname();
	const [menuOpen, setMenuOpen] = useState(false);
	const [searchOpen, setSearchOpen] = useState(false);

	useEffect(() => {
		function onKey(event: KeyboardEvent) {
			if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
				event.preventDefault();
				setMenuOpen(false);
				setSearchOpen(true);
			}
		}
		window.addEventListener('keydown', onKey);
		return () => window.removeEventListener('keydown', onKey);
	}, []);

	function closeMenu() {
		setMenuOpen(false);
	}

	function openSearch() {
		setMenuOpen(false);
		setSearchOpen(true);
	}

	return (
		<div className="landing">
			<div className={`landing-body${searchOpen ? ' is-blurred' : ''}`}>
				<header className="hall-nav">
					<a href="/" className="hall-logo no-underline" aria-label="SPŠT knižnica">
						<BookOpen className="size-6" />
					</a>
					<nav className="hall-desk-links" aria-label="Hlavná navigácia">
						<a href="/" aria-current={path === '/' ? 'page' : undefined}>
							Fond
						</a>
						<a href="/discover" aria-current={path.startsWith('/discover') ? 'page' : undefined}>
							Objavovať
						</a>
						<a href="/holdings" aria-current={path.startsWith('/holdings') ? 'page' : undefined}>
							Všetky knihy
						</a>
						<a href="/books">Katalóg</a>
						<a href="/authors">Autori</a>
					</nav>
					<div className="hall-tools">
						<button type="button" className="hall-search-btn" onClick={openSearch} aria-label="Hľadať knihu">
							<Search className="size-4" />
							<span>Hľadať knihu</span>
						</button>
						<ThemeToggle variant="hall" />
						<a
							className="hall-login no-underline"
							href={user ? '/loans' : '/login'}
							aria-label={user ? 'Moje knihy' : 'Prihlásiť sa'}
						>
							<User className="size-4" />
							<span>{user ? 'Moje knihy' : 'Prihlásiť sa'}</span>
						</a>
						<button
							type="button"
							className={`hall-menu-btn${menuOpen ? ' is-open' : ''}`}
							aria-controls="landing-menu"
							aria-expanded={menuOpen}
							aria-label={menuOpen ? 'Zavrieť menu' : 'Otvoriť menu'}
							onClick={() => setMenuOpen((open) => !open)}
						>
							<span />
							<span />
							<span />
						</button>
					</div>
				</header>

				{menuOpen ? (
					<nav className="hall-drawer" id="landing-menu" aria-label="Mobilné menu">
						<a href="/" onClick={closeMenu}>
							Fond
						</a>
						<a href="/discover" onClick={closeMenu}>
							Objavovať
						</a>
						<a href="/holdings" onClick={closeMenu}>
							Všetky knihy
						</a>
						<a href="/books" onClick={closeMenu}>
							Katalóg
						</a>
						<a href="/departments" onClick={closeMenu}>
							Odbory
						</a>
						<a href="/authors" onClick={closeMenu}>
							Autori
						</a>
						{user ? (
							<>
								<a href="/profile" onClick={closeMenu}>
									Môj profil
								</a>
								<a href="/loans" onClick={closeMenu}>
									Moje knihy
								</a>
								{admin ? (
									<a href="/admin" onClick={closeMenu}>
										Pult
									</a>
								) : null}
							</>
						) : (
							<a href="/login" onClick={closeMenu}>
								Prihlásiť sa
							</a>
						)}
						<div className="hall-drawer-tools">
							<ThemeToggle variant="hall" />
							<button type="button" className="hall-search-btn is-mobile" onClick={openSearch}>
								<Search className="size-4" />
								<span>Hľadať knihu</span>
							</button>
						</div>
					</nav>
				) : null}

				{children}
				<Footer tone="hall" />
			</div>
			<CatalogSearch preview={searchPreview} open={searchOpen} onOpenChange={setSearchOpen} />
		</div>
	);
}
