// src/lib/components/Handbook.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import { flattenPageTree, type PageTree } from 'fumadocs-svelte';
	import { docsHref } from '$lib/docs/href';
	import { sortDocChapters } from '$lib/docs/order';
	import ThemeToggle from '$lib/components/ThemeToggle.svelte';
	import type { Snippet } from 'svelte';

	let { tree, children }: { tree: PageTree; children: Snippet } = $props();

	const chapters = $derived(sortDocChapters(flattenPageTree(tree)));
	let open = $state(false);

	function current(url: string) {
		return page.url.pathname === url || (url === '/docs' && page.url.pathname === '/docs/');
	}

	function close() {
		open = false;
	}

	async function openTour() {
		const { startTour, markTourSeen } = await import('$lib/tour');
		await startTour(markTourSeen);
	}
</script>

<div class="handbook" id="obsah">
	<header class="handbook-bind">
		<a class="handbook-mark no-underline" href={resolve('/')} data-tour="docs-mark">
			<span>SPŠT</span>
			knižnica
		</a>
		<button type="button" class="handbook-toc-btn" onclick={() => (open = !open)} aria-expanded={open}>
			Kapitoly
		</button>
		<div class="handbook-tools">
			<button
				type="button"
				class="handbook-tour-btn"
				onclick={openTour}
				aria-label="Prehliadka príručky"
			>
				Prehliadka
			</button>
			<a class="handbook-cta no-underline" href={resolve('/discover')} data-tour="docs-fund">Do fondu</a>
			<ThemeToggle />
		</div>
	</header>

	<div class="handbook-spread">
		{#if open}
			<button type="button" class="handbook-scrim" aria-label="Zavrieť kapitoly" onclick={close}></button>
		{/if}

		<aside class="handbook-index" class:is-open={open} data-tour="docs-chapters">
			<p class="handbook-spine" aria-hidden="true"><span>Príručka</span></p>
			<div class="handbook-index-body">
				<p class="handbook-kicker">Kapitoly</p>
				<nav aria-label="Kapitoly príručky">
					{#each chapters as chapter, i (chapter.url)}
						<a
							class="handbook-item no-underline"
							class:is-on={current(chapter.url)}
							href={docsHref(chapter.url)}
							aria-current={current(chapter.url) ? 'page' : undefined}
							onclick={close}
						>
							<em>{String(i + 1).padStart(2, '0')}</em>
							<span>{chapter.data.title}</span>
						</a>
					{/each}
				</nav>
			</div>
		</aside>

		<div class="handbook-paper">
			{@render children()}
		</div>
	</div>
</div>

// src/components/Handbook.tsx
'use client';

import { type ReactNode, useState } from 'react';
import { FolioLink as Link } from '@/components/FolioLink';
import { ThemeToggle } from '@/components/ThemeToggle';
import { docsHref } from '@/docs/href';

export type HandbookChapter = {
	url: string;
	title: string;
};

export function Handbook({
	chapters,
	currentUrl,
	children
}: {
	chapters: HandbookChapter[];
	currentUrl: string;
	children: ReactNode;
}) {
	const [open, setOpen] = useState(false);

	function current(url: string) {
		return currentUrl === url || (url === '/docs' && currentUrl === '/docs/');
	}

	async function openTour() {
		const { startTour, markTourSeen } = await import('@/tour');
		await startTour(markTourSeen);
	}

	return (
		<div className="handbook" id="obsah">
			<header className="handbook-bind">
				<Link className="handbook-mark" href="/" data-tour="docs-mark">
					<span>SPŠT</span>
					knižnica
				</Link>
				<button
					type="button"
					className="handbook-toc-btn"
					onClick={() => setOpen((value) => !value)}
					aria-expanded={open}
				>
					Kapitoly
				</button>
				<div className="handbook-tools">
					<button
						type="button"
						className="handbook-tour-btn"
						onClick={openTour}
						aria-label="Prehliadka príručky"
					>
						Prehliadka
					</button>
					<Link className="handbook-cta" href="/discover" data-tour="docs-fund">
						Do fondu
					</Link>
					<ThemeToggle variant="hall" />
				</div>
			</header>

			<div className="handbook-spread">
				{open ? (
					<button
						type="button"
						className="handbook-scrim"
						aria-label="Zavrieť kapitoly"
						onClick={() => setOpen(false)}
					/>
				) : null}

				<aside className={`handbook-index${open ? ' is-open' : ''}`} data-tour="docs-chapters">
					<p className="handbook-spine" aria-hidden="true">
						<span>Príručka</span>
					</p>
					<div className="handbook-index-body">
						<p className="handbook-kicker">Kapitoly</p>
						<nav aria-label="Kapitoly príručky">
							{chapters.map((chapter, index) => (
								<Link
									key={chapter.url}
									className={`handbook-item${current(chapter.url) ? ' is-on' : ''}`}
									href={docsHref(chapter.url)}
									aria-current={current(chapter.url) ? 'page' : undefined}
									onClick={() => setOpen(false)}
								>
									<em>{String(index + 1).padStart(2, '0')}</em>
									<span>{chapter.title}</span>
								</Link>
							))}
						</nav>
					</div>
				</aside>

				<div className="handbook-paper">{children}</div>
			</div>
		</div>
	);
}
