// src/lib/components/PultNav.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { pultTablesFor } from '$lib/admin';

	let { manage = true }: { manage?: boolean } = $props();
	const tabs = $derived(pultTablesFor(manage));

	function on(path: string) {
		if (path === '/admin') return page.url.pathname === '/admin' || page.url.pathname === '/admin/';
		return page.url.pathname.startsWith(path);
	}
</script>

<nav class="pult-tabs" aria-label="Kartotéka pultu">
	{#each tabs as item, i (item.href)}
		<a class="pult-tab" class:is-on={on(item.href)} href={item.href} style="animation-delay: {i * 40}ms">
			<em>{item.code}</em>
			{item.label}
		</a>
	{/each}
</nav>

// src/components/PultNav.tsx
import { pultTablesFor } from '@/desk/admin';

export function PultNav({ manage = true, pathname }: { manage?: boolean; pathname: string }) {
	const tabs = pultTablesFor(manage);

	function on(path: string) {
		if (path === '/admin') return pathname === '/admin' || pathname === '/admin/';
		return pathname.startsWith(path);
	}

	return (
		<nav className="pult-tabs" aria-label="Kartotéka pultu">
			{tabs.map((item, i) => (
				<a
					key={item.href}
					className={`pult-tab${on(item.href) ? ' is-on' : ''}`}
					href={item.href}
					style={{ animationDelay: `${i * 40}ms` }}
				>
					<em>{item.code}</em>
					{item.label}
				</a>
			))}
		</nav>
	);
}
