// src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { toggleMode, mode } from 'mode-watcher';
	import SunIcon from '@lucide/svelte/icons/sun';
	import MoonIcon from '@lucide/svelte/icons/moon';

	let { variant = 'desk' }: { variant?: 'desk' | 'hall' } = $props();

	const isDark = $derived(mode.current === 'dark');
	const label = $derived(isDark ? 'Zapnúť svetlé zobrazenie' : 'Zapnúť tmavé zobrazenie');
</script>

<button
	type="button"
	class={variant === 'hall'
		? 'hall-theme-btn'
		: 'grid size-10 cursor-pointer place-items-center rounded-full bg-primary text-primary-foreground hover:opacity-80 focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-ring'}
	onclick={toggleMode}
	aria-label={label}
	title={label}
>
	{#if isDark}
		<SunIcon class="size-4" />
	{:else}
		<MoonIcon class="size-4" />
	{/if}
</button>

<style>
	.hall-theme-btn {
		display: grid;
		place-items: center;
		width: 2.35rem;
		height: 2.35rem;
		border: 0;
		border-radius: 999px;
		background: var(--ink);
		color: var(--page);
		cursor: pointer;
	}

	.hall-theme-btn:hover {
		opacity: 0.82;
	}

	.hall-theme-btn:focus-visible {
		outline: 2px solid var(--ink);
		outline-offset: 3px;
	}
</style>

// src/components/ThemeToggle.tsx
'use client';

import { useTheme } from 'next-themes';
import { Moon, Sun } from 'lucide-react';
import { useEffect, useState } from 'react';
import './theme-toggle.css';

export function ThemeToggle({ variant = 'desk' }: { variant?: 'desk' | 'hall' }) {
	const { resolvedTheme, setTheme } = useTheme();
	const [mounted, setMounted] = useState(false);
	useEffect(() => setMounted(true), []);
	const isDark = mounted && resolvedTheme === 'dark';
	const label = isDark ? 'Zapnúť svetlé zobrazenie' : 'Zapnúť tmavé zobrazenie';

	return (
		<button
			type="button"
			className={
				variant === 'hall'
					? 'hall-theme-btn'
					: 'grid size-9 cursor-pointer place-items-center rounded-full bg-primary text-primary-foreground hover:opacity-80 focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-ring sm:size-10'
			}
			onClick={() => setTheme(isDark ? 'light' : 'dark')}
			aria-label={label}
			title={label}
		>
			{isDark ? <Sun className="size-4" /> : <Moon className="size-4" />}
		</button>
	);
}
